### ISSUE TITLE
Test Project App.config settings are not picked up

### ISSUE THREAD

**Issue by mpareja** [codereflection/Giles#12]
I have a test project that contains an App.config file.  The settings in the application configuration file are not picked up by Giles when executing tests.

You can reproduce this problem in the following repository.  Tests pass using NUnit GUI, TDD.NET and ReSharper.

https://github.com/mpareja/ConfigAutoMapper

**Comment by codereflection** [comment]
Fixed issue in dev branch, will be included in the next release.

**Comment by codereflection** [comment]
Mario - I pulled down your ConfigAutoMapper and the Giles Dev branch does pass all 18 tests now.

**Comment by mpareja** [comment]
Nice, thanks! Would love to have done this, but I just bought a house, so coding time has unfortunately been cut way down at the moment!
