### ISSUE TITLE
No support for mstest

### ISSUE THREAD

**Issue by MichalSznajder** [codereflection/Giles#48]
I just wanted to tried giles but it seems there is no support for MsTest.

Any chance of adding it?

**Comment by codereflection** [comment]
Thank you for the interest in Giles.

Unfortunately MSTest support will not be included in the foreseeable future. MSTest is a difficult framework to deal with, and I do not have the time to spend on it.

I recommend looking at NCrunch (https://www.ncrunch.net/) or Mighty Moose (http://continuoustests.com/), which both support MSTest.

Cheers,
Jeff

**Comment by reidev275** [comment]
I did some research on this about a year ago.  Basically there were two ways I found to deal with mstest.    
1. use an nunit adapter, or 
2. use reflection to instantiate the internal .net class responsible for running mstest.  

Both of those seemed less than ideal so I stopped using mstest.

**Comment by NotMyself** [comment]
For what it's worth, most of the public microsoft repositories seem to be using XUnit. See the [project file for MVC5](https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNet.Mvc.Core.Test/project.json).

**Comment by MichalSznajder** [comment]
I also used NUnit for years but in my current situation I am stuck with MsTest. :cry: 

@codereflection Would you accept pull request that uses MsTest.exe and than result XML file is parsed and returned to Giles (like described in http://stackoverflow.com/a/2595828/501) ?

**Comment by codereflection** [comment]
I would probably be OK with that.
